/**
 * InboxEntry v1 — the 192 bytes that make a shielded deposit into a k1-arm
 * account something other than destroying the coin.
 *
 * WHY THIS EXISTS (2026/09/16)
 * ----------------------------
 * `deposit_shielded(coin, entry)` on the reference account takes two arguments.
 * The coin moves into the contract's Zswap balance. The `entry` is 192 opaque
 * bytes the contract stores in an append-only map and never reads: the
 * DEPOSITOR — this service, in the two paths that pay accounts — encrypts the
 * coin's description to the account's advertised `enc_key`, and only the
 * account's owner can open it.
 *
 * That second argument is the only channel the description travels on. What a
 * shielded coin IS — nonce, colour, value, and its position in the commitment
 * tree — never reaches public state (MIP-0012 §6.1), and the owner's
 * `held_coin` witness must answer with all of it before the account can spend.
 * A deposit with a placeholder entry still lands, and the coin is then gone: it
 * is in the contract, and nobody, including the owner, can ever name it again.
 * That is why `./accountModule.ts` refused rather than guessing, and this is
 * the module that lets it stop.
 *
 * NOTHING HERE IS INVENTED. It is the reference's `contract/src/wallet/
 * inbox.ts` (MIP-0012 §6.4), primitive for primitive, offset for offset:
 *
 *   | offset | length | field                                     |
 *   |--------|--------|-------------------------------------------|
 *   | 0      | 1      | version = 0x01                            |
 *   | 1      | 1      | suite   = 0x01 (X25519+HKDF-SHA256+GCM)   |
 *   | 2      | 32     | ephemeral X25519 public key               |
 *   | 34     | 12     | AEAD nonce                                |
 *   | 46     | 16     | AEAD tag                                  |
 *   | 62     | 80     | ciphertext                                |
 *   | 142    | 50     | zero padding                              |
 *
 * The 80-byte plaintext is coin nonce (32) ‖ colour (32) ‖ value as an unsigned
 * 128-bit big-endian integer (16). The AEAD key is
 * HKDF-SHA256(ikm = X25519(ephemeral secret, enc_key), salt = empty,
 * info = "midnight:custody:inbox:v1", L = 32); the associated data is the first
 * two container bytes, so a rewritten version or suite byte fails
 * authentication instead of being mis-parsed. Writers zero the padding and
 * readers ignore it, which is what keeps every entry the same size whatever it
 * holds.
 *
 * THE DEMO HAS A SECOND COPY OF THIS, AND THAT IS DELIBERATE. The client's
 * `examples/passport-demo/src/identity/k1Inbox.ts` runs in a browser and uses
 * `@noble/curves` and `crypto.subtle`; this one is a Node service and uses
 * `node:crypto`, as the reference does. They share no code, which is precisely
 * why both are tested against the SAME fixtures — `test/fixtures/inbox-v1.json`,
 * generated by running the reference's own implementation. Two implementations
 * that agree with themselves and not with each other is a failure that does not
 * surface until a coin is already stranded.
 */

import {
  createCipheriv,
  createDecipheriv,
  createPrivateKey,
  createPublicKey,
  diffieHellman,
  generateKeyPairSync,
  hkdfSync,
  randomBytes,
} from 'node:crypto';
import { Buffer } from 'node:buffer';

/** The container's fixed size. `Bytes<192>` in the contract, and never less. */
export const INBOX_ENTRY_SIZE = 192;

/** Container version. A reader skips an entry carrying any other value. */
export const INBOX_ENTRY_VERSION = 0x01;

/** Suite 1: X25519 ‖ HKDF-SHA256 ‖ AES-256-GCM. The only one defined. */
export const INBOX_ENTRY_SUITE = 0x01;

/** The sealed coin description, before padding. */
export const INBOX_PLAINTEXT_SIZE = 80;

/**
 * The HKDF info string, byte for byte.
 *
 * It is what separates this key schedule from any other that might one day
 * share an X25519 shared secret with it. Changing a character makes every entry
 * ever written unreadable, which is why it is a named constant rather than a
 * literal at the call site.
 */
export const INBOX_HKDF_INFO = 'midnight:custody:inbox:v1';

const EPHEMERAL_OFFSET = 2;
const NONCE_OFFSET = 34;
const TAG_OFFSET = 46;
const CIPHERTEXT_OFFSET = 62;
const NONCE_SIZE = 12;
const TAG_SIZE = 16;
const KEY_SIZE = 32;

/*
 * `node:crypto` only speaks DER and JWK for raw key material, so a raw 32-byte
 * X25519 key is wrapped into SPKI or PKCS8 with these fixed prefixes. Straight
 * from the reference; they are constants of the encoding, not of any key.
 */
const SPKI_PREFIX = Buffer.from('302a300506032b656e032100', 'hex');
const PKCS8_PREFIX = Buffer.from('302e020100300506032b656e04220420', 'hex');

/**
 * An account's X25519 encryption keypair.
 *
 * The public half is what a contract advertises as `enc_key`. The secret half
 * is the viewing capability (MIP-0012 R9) and this service never holds one: it
 * is a DEPOSITOR, it seals and never opens. {@link generateEncKeyPair} exists
 * so the tests can be a recipient, and for no other reason.
 */
export interface EncKeyPair {
  readonly publicKey: Uint8Array;
  readonly secretKey: Uint8Array;
}

/** A coin description as an entry carries it. No position: see below. */
export interface InboxCoin {
  readonly nonce: Uint8Array;
  readonly color: Uint8Array;
  readonly value: bigint;
}

export function generateEncKeyPair(): EncKeyPair {
  const { publicKey, privateKey } = generateKeyPairSync('x25519');
  const spki = publicKey.export({ type: 'spki', format: 'der' });
  const pkcs8 = privateKey.export({ type: 'pkcs8', format: 'der' });
  return {
    publicKey: new Uint8Array(spki.subarray(spki.length - KEY_SIZE)),
    secretKey: new Uint8Array(pkcs8.subarray(pkcs8.length - KEY_SIZE)),
  };
}

function x25519(rawSecret: Uint8Array, rawPeerPublic: Uint8Array): Buffer {
  const privateKey = createPrivateKey({
    key: Buffer.concat([PKCS8_PREFIX, Buffer.from(rawSecret)]),
    type: 'pkcs8',
    format: 'der',
  });
  const publicKey = createPublicKey({
    key: Buffer.concat([SPKI_PREFIX, Buffer.from(rawPeerPublic)]),
    type: 'spki',
    format: 'der',
  });
  return diffieHellman({ privateKey, publicKey });
}

/** RFC 5869 with an empty salt — the RFC's own default — and L = 32. */
function deriveAeadKey(ikm: Buffer): Buffer {
  return Buffer.from(hkdfSync('sha256', ikm, Buffer.alloc(0), INBOX_HKDF_INFO, KEY_SIZE));
}

/**
 * The 80-byte plaintext: nonce ‖ colour ‖ value, big-endian.
 *
 * Throws rather than truncating a value that will not fit. A truncated value is
 * an entry that says the coin is worth less than it is, and an owner who
 * under-spends it for ever.
 */
export function encodeInboxCoin(coin: InboxCoin): Buffer {
  requireLength('a coin nonce', coin.nonce, KEY_SIZE);
  requireLength('a colour', coin.color, KEY_SIZE);
  if (typeof coin.value !== 'bigint' || coin.value < 0n || coin.value > (1n << 128n) - 1n) {
    throw new Error(`An inbox entry cannot carry a value of ${String(coin.value)}.`);
  }
  const out = Buffer.alloc(INBOX_PLAINTEXT_SIZE);
  Buffer.from(coin.nonce).copy(out, 0);
  Buffer.from(coin.color).copy(out, KEY_SIZE);
  let remaining = coin.value;
  for (let index = 15; index >= 0; index -= 1) {
    out[64 + index] = Number(remaining & 0xffn);
    remaining >>= 8n;
  }
  return out;
}

/** The inverse. Null on anything that is not exactly eighty bytes. */
export function decodeInboxCoin(plaintext: Uint8Array): InboxCoin | null {
  if (plaintext.length !== INBOX_PLAINTEXT_SIZE) return null;
  const buffer = Buffer.from(plaintext);
  let value = 0n;
  for (let index = 0; index < 16; index += 1) value = (value << 8n) | BigInt(buffer[64 + index]);
  return {
    nonce: new Uint8Array(buffer.subarray(0, KEY_SIZE)),
    color: new Uint8Array(buffer.subarray(KEY_SIZE, 64)),
    value,
  };
}

function requireLength(what: string, bytes: Uint8Array | undefined, length: number): void {
  if (!(bytes instanceof Uint8Array) || bytes.length !== length) {
    throw new Error(`An inbox entry needs ${what} of ${length} bytes, not ${String(bytes?.length)}.`);
  }
}

/**
 * Seal a coin description to an account's advertised `enc_key`.
 *
 * A FRESH EPHEMERAL KEY PER ENTRY, and its secret half never leaves this
 * function. So this service cannot read back what it deposited, which is the
 * property that makes the inbox a private channel between depositor and owner
 * rather than a public record of who paid whom — and it is why the two deposit
 * paths confirm against `inbox_count` growing rather than against a balance
 * they could read.
 */
export function sealInboxEntry(recipientEncKey: Uint8Array, coin: InboxCoin): Uint8Array {
  requireLength('an account encryption key', recipientEncKey, KEY_SIZE);
  const plaintext = encodeInboxCoin(coin);
  const ephemeral = generateEncKeyPair();
  const key = deriveAeadKey(x25519(ephemeral.secretKey, recipientEncKey));
  const nonce = randomBytes(NONCE_SIZE);
  const associatedData = Buffer.from([INBOX_ENTRY_VERSION, INBOX_ENTRY_SUITE]);

  const cipher = createCipheriv('aes-256-gcm', key, nonce);
  cipher.setAAD(associatedData);
  const ciphertext = Buffer.concat([cipher.update(plaintext), cipher.final()]);
  const tag = cipher.getAuthTag();

  const entry = Buffer.alloc(INBOX_ENTRY_SIZE); // the trailing padding stays zero
  entry[0] = INBOX_ENTRY_VERSION;
  entry[1] = INBOX_ENTRY_SUITE;
  Buffer.from(ephemeral.publicKey).copy(entry, EPHEMERAL_OFFSET);
  nonce.copy(entry, NONCE_OFFSET);
  tag.copy(entry, TAG_OFFSET);
  ciphertext.copy(entry, CIPHERTEXT_OFFSET);
  return new Uint8Array(entry);
}

/**
 * Open an entry with an account's viewing secret, or null.
 *
 * This service never does this in anger — it has no account's secret and wants
 * none. It is here because a codec that can only write is a codec nothing can
 * check, and because the cross-implementation fixtures are read through it.
 *
 * NULL FOR EVERY KIND OF NO, which is the §6.5 rule: an entry addressed to
 * somebody else and an entry written deliberately to stop a walk are the same
 * event from here, and the only safe response to both is the next index.
 */
export function openInboxEntry(encSecretKey: Uint8Array, entry: Uint8Array): InboxCoin | null {
  if (!(entry instanceof Uint8Array) || entry.length !== INBOX_ENTRY_SIZE) return null;
  const buffer = Buffer.from(entry);
  if (buffer[0] !== INBOX_ENTRY_VERSION || buffer[1] !== INBOX_ENTRY_SUITE) return null;
  try {
    const ephemeralPublic = new Uint8Array(
      buffer.subarray(EPHEMERAL_OFFSET, EPHEMERAL_OFFSET + KEY_SIZE),
    );
    const nonce = buffer.subarray(NONCE_OFFSET, NONCE_OFFSET + NONCE_SIZE);
    const tag = buffer.subarray(TAG_OFFSET, TAG_OFFSET + TAG_SIZE);
    const ciphertext = buffer.subarray(
      CIPHERTEXT_OFFSET,
      CIPHERTEXT_OFFSET + INBOX_PLAINTEXT_SIZE,
    );
    const key = deriveAeadKey(x25519(encSecretKey, ephemeralPublic));
    /* `authTagLength` pins the full sixteen-byte tag. The fixed layout already
       guarantees it; saying so makes the invariant the cipher's too. */
    const decipher = createDecipheriv('aes-256-gcm', key, nonce, { authTagLength: TAG_SIZE });
    decipher.setAAD(buffer.subarray(0, 2));
    decipher.setAuthTag(tag);
    return decodeInboxCoin(Buffer.concat([decipher.update(ciphertext), decipher.final()]));
  } catch {
    return null; // not ours, or poisoned
  }
}
